<% if(data.post['error_test']){ %>
{
    "error_response": {
        "code": "SH5PXXXXXX0001",
        "host" : "<%= data['res'] %>",
        "msg": "错误的商品"
    }
}
<% }else{ %>
{
    "hfive_weidian_store_get_response": {
        "id": 1,
        "uid": 1,
        "name": "小新的店",
        "edit_name_count": 4,
        "logo": "images/default_shop_2.jpg",
        "sale_category_fid": 1,
        "sale_category_id": 1,
        "linkman": "Bessy",
        "tel": "15942490296",
        "intro": "小新的店",
        "approve": "0",
        "status": "0",
        "date_added": "1441610222",
        "service_tel": "15942490296",
        "service_qq": "23117051",
        "service_weixin": "zengxin",
        "bind_weixin": 0,
        "weixin_name": "小新的店",
        "weixin_original_id": "gh_ce89dcb24ea1",
        "weixin_id": "gh_ce89dcb24ea1",
        "qq": "23117051",
        "open_weixin": "0",
        "buyer_selffetch": "0",
        "buyer_selffetch_name": "小新",
        "pay_agent": "0",
        "open_nav": 0,
        "nav_style_id": 1,
        "use_nav_pages": "1",
        "open_ad": 0,
        "has_ad": 0,
        "ad_position": 0,
        "use_ad_pages": "1",
        "date_edited": "1441610222",
        "income": 0.18,
        "balance": 0.02,
        "unbalance": 0.16,
        "withdrawal_amount": 0.45,
        "withdrawal_type": 0,
        "bank_id": 0,
        "bank_card": "42342342423424234",
        "bank_card_user": "小新",
        "opening_bank": "icbc",
        "last_edit_time": "1441610222",
        "physical_count": 100,
        "drp_supplier_id": 1,
        "drp_level": 0,
        "collect": 100,
        "wxpay": 0,
        "open_drp_approve": 0,
        "drp_approve": 1,
        "drp_profit": 0,
        "drp_profit_withdrawal": 0,
        "attention_num": 100,
        "pigcmstoken": "",
        "template_cat_id": 0,
        "template_id": 0,
        "open_friend": 0,
        "offline_payment": 0,
        "open_logistics": 0,
        "open_service": 0,
        "open_drp_guidance": 0,
        "creator": "赵钱孙李",
        "owner": "赵钱孙李",
        "rx_inserttime": "1441610222",
        "rx_updatetime": "1441610222",
        "update_user_id": 1,
        "data_uuid": "",
        "use_yn": "Y",
        "company_key": "ff8080814d8922fe014d8e18c9fd0004",
        "company_id": 1
    }
}
<%}%>