{
    "hfive_core_tag_microapp_mypage_tree_response":{
    "error": true,
    "message": "获取分类成功",
    "data": [
    {
        "id": "624",
        "tid": "0000000006",
        "title": "未分类",
        "number": "-14",
        "pid": "0",
        "issystem": "1",
        "nuclass": "0000000001",
        "status": "1",
        "create_time": null,
        "create_id": null,
        "update_id": null,
        "update_time": null,
        "gt_id": "0",
        "company_id": "19",
        "creator": "35",
        "owner": "35",
        "create_user_id": "35",
        "rx_inserttime": "2015-05-26 10:57:19",
        "update_user_id": "35",
        "rx_updatetime": "2015-05-26 10:57:19",
        "data_uuid": null,
        "tpl_classfiy": "C",
        "company_key": null
    },
    {
        "id": "1297",
        "tid": "0000000006",
        "title": "1",
        "number": "-5",
        "pid": "0",
        "issystem": "0",
        "nuclass": null,
        "status": "1",
        "create_time": null,
        "create_id": null,
        "update_id": null,
        "update_time": null,
        "gt_id": "0",
        "company_id": "19",
        "creator": "35",
        "owner": "35",
        "create_user_id": "35",
        "rx_inserttime": "2015-05-27 11:48:11",
        "update_user_id": "35",
        "rx_updatetime": "2015-05-27 11:48:11",
        "data_uuid": null,
        "tpl_classfiy": "C",
        "company_key": null
    },
    {
        "id": "1335",
        "tid": "0000000006",
        "title": "白玩测试",
        "number": "-3",
        "pid": "624",
        "issystem": "0",
        "nuclass": null,
        "status": "1",
        "create_time": null,
        "create_id": null,
        "update_id": null,
        "update_time": null,
        "gt_id": "0",
        "company_id": "19",
        "creator": "33",
        "owner": "33",
        "create_user_id": "33",
        "rx_inserttime": "2015-06-25 14:56:27",
        "update_user_id": "33",
        "rx_updatetime": "2015-06-25 14:56:27",
        "data_uuid": null,
        "tpl_classfiy": "C",
        "company_key": null
    },
    {
        "id": "1394",
        "tid": "0000000006",
        "title": "郑新测试店铺",
        "number": "-1",
        "pid": "624",
        "issystem": "0",
        "nuclass": null,
        "status": "1",
        "create_time": null,
        "create_id": null,
        "update_id": null,
        "update_time": null,
        "gt_id": "0",
        "company_id": "19",
        "creator": "32",
        "owner": "32",
        "create_user_id": "32",
        "rx_inserttime": "2015-07-29 14:27:10",
        "update_user_id": "32",
        "rx_updatetime": "2015-07-29 14:27:10",
        "data_uuid": null,
        "tpl_classfiy": "C",
        "company_key": null
    },
    {
        "id": "1405",
        "tid": "0000000006",
        "title": "微店",
        "number": "0",
        "pid": "0",
        "issystem": "1",
        "nuclass": "0000000000",
        "status": "1",
        "create_time": null,
        "create_id": null,
        "update_id": null,
        "update_time": null,
        "gt_id": "0",
        "company_id": "19",
        "creator": null,
        "owner": null,
        "create_user_id": null,
        "rx_inserttime": "2015-05-26 10:57:19",
        "update_user_id": null,
        "rx_updatetime": null,
        "data_uuid": null,
        "tpl_classfiy": "C",
        "company_key": null
    },
    {
        "id": "1436",
        "tid": "0000000006",
        "title": "上传页面",
        "number": "-14",
        "pid": "0",
        "issystem": "1",
        "nuclass": "0000000001",
        "status": "1",
        "create_time": null,
        "create_id": null,
        "update_id": null,
        "update_time": null,
        "gt_id": "0",
        "company_id": "19",
        "creator": null,
        "owner": null,
        "create_user_id": null,
        "rx_inserttime": "2015-05-26 10:57:19",
        "update_user_id": null,
        "rx_updatetime": null,
        "data_uuid": null,
        "tpl_classfiy": "C",
        "company_key": null
    },
    {
        "id": "1692",
        "tid": "0000000006",
        "title": "我的页面",
        "number": "0",
        "pid": "0",
        "issystem": "0",
        "nuclass": null,
        "status": "1",
        "create_time": null,
        "create_id": null,
        "update_id": null,
        "update_time": null,
        "gt_id": "0",
        "company_id": "19",
        "creator": "32",
        "owner": "32",
        "create_user_id": "32",
        "rx_inserttime": "2015-09-16 11:12:12",
        "update_user_id": "32",
        "rx_updatetime": "2015-09-16 11:12:12",
        "data_uuid": null,
        "tpl_classfiy": "C",
        "company_key": null
    },
    {
        "id": "1711",
        "tid": "0000000006",
        "title": "1212",
        "number": "5",
        "pid": "0",
        "issystem": "0",
        "nuclass": null,
        "status": "1",
        "create_time": null,
        "create_id": null,
        "update_id": null,
        "update_time": null,
        "gt_id": "0",
        "company_id": "19",
        "creator": "32",
        "owner": "32",
        "create_user_id": "32",
        "rx_inserttime": "2015-10-29 11:11:26",
        "update_user_id": "32",
        "rx_updatetime": "2015-10-29 11:11:26",
        "data_uuid": null,
        "tpl_classfiy": "C",
        "company_key": null
    },
    {
        "id": "1762",
        "tid": "0000000006",
        "title": "我是测试",
        "number": "0",
        "pid": "0",
        "issystem": "0",
        "nuclass": null,
        "status": "1",
        "create_time": null,
        "create_id": null,
        "update_id": null,
        "update_time": null,
        "gt_id": "0",
        "company_id": "19",
        "creator": "32",
        "owner": "32",
        "create_user_id": "32",
        "rx_inserttime": "2016-01-20 15:30:37",
        "update_user_id": "32",
        "rx_updatetime": "2016-01-20 15:30:37",
        "data_uuid": null,
        "tpl_classfiy": "C",
        "company_key": null
    },
    {
        "id": "1763",
        "tid": "0000000006",
        "title": "我是测试主页面",
        "number": "0",
        "pid": "1762",
        "issystem": "0",
        "nuclass": null,
        "status": "1",
        "create_time": null,
        "create_id": null,
        "update_id": null,
        "update_time": null,
        "gt_id": "0",
        "company_id": "19",
        "creator": "32",
        "owner": "32",
        "create_user_id": "32",
        "rx_inserttime": "2016-01-20 15:30:55",
        "update_user_id": "32",
        "rx_updatetime": "2016-01-20 15:30:55",
        "data_uuid": null,
        "tpl_classfiy": "C",
        "company_key": null
    }
        ]
    }
}